# Generated by Django 5.2 on 2025-05-12 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('secondTitle', models.CharField(max_length=200, verbose_name='عنوان دوم')),
                ('slug', models.SlugField(allow_unicode=True, max_length=500, unique=True)),
                ('bodySection1', models.TextField(verbose_name='بخش اول محتوا')),
                ('bodySection2', models.TextField(verbose_name='بخش دوم محتوا')),
                ('bodySection3', models.TextField(verbose_name='بخش سه محتوا')),
                ('bodySection4', models.TextField(verbose_name='بخش چهارم محتوا')),
                ('bodyPoint', models.TextField(max_length=400, verbose_name='نکته')),
                ('mainPoster', models.ImageField(upload_to='%Y/%m/%d', verbose_name='عکس')),
                ('secondPoster', models.ImageField(upload_to='%Y/%m/%d', verbose_name='عکس دوم')),
                ('thirdPoster', models.ImageField(upload_to='%Y/%m/%d', verbose_name='عکس سوم')),
                ('postersTitle', models.CharField(max_length=100, verbose_name='عنوان عکس ها')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='تاریخ ساخت')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
        ),
    ]
